name: Copywrite

on:
  push:
    tags:
      - v*
    branches:
      - main
      - jasonpilz/copyright-headers
  pull_request:
  workflow_dispatch:

jobs:
  copywrite:
    - name: Install Copywrite
      uses: hashicorp/setup-copywrite@v1
      with:
        version: v0.1.2

    - name: Run Copywrite Header Compliance
      run: copywrite headers --plan
