name: Copywrite

on:
  push:
    tags:
      - v*
    branches:
      - main
      - jasonpilz/copyright-headers
  pull_request:
  workflow_dispatch:

jobs:
  copywrite:
    name: Run Header Copyright
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Install Copywrite
        id: install
        uses: hashicorp/setup-copywrite@v1
        with:
          version: v0.1.2

      - name: Output Installed Copywrite Version
        run: echo "Installed Copywrite CLI ${{steps.install.outputs.version}}"

      - name: Run Copywrite Header Compliance
        run: copywrite headers --plan
